# Generated by Django 3.0.4 on 2024-03-12 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='* Campo obrigatório', max_length=100, verbose_name='Nome do fornecedor *')),
                ('cnpj', models.CharField(help_text='* Campo obrigatório', max_length=15, unique=True, verbose_name='CNPJ *')),
                ('cidade', models.CharField(help_text='* Campo obrigatório', max_length=100, verbose_name='Cidade *')),
                ('tipo_fornecedor', models.CharField(choices=[('BRASILEIRO', 'Brasileiro'), ('EXTERNO', 'Externo')], help_text='* Campo obrigatório', max_length=10, verbose_name='Tipo de fornecedor *')),
                ('is_active', models.BooleanField(default=True, help_text='Se ativo, o fornecedor pode ser usado no sistema', verbose_name='Ativo')),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, verbose_name='Hash')),
            ],
            options={
                'verbose_name': 'fornecedor',
                'verbose_name_plural': 'fornecedores',
                'ordering': ['-is_active', 'tipo_fornecedor', 'nome'],
            },
        ),
    ]
