# Generated by Django 3.0.4 on 2020-11-24 13:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Unidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='* Campos obrigatórios', max_length=100, unique=True, verbose_name='Nome da Unidade de Atendimento *')),
                ('endereco', models.CharField(max_length=150, verbose_name='Rua, número, complemento, bairro e CEP *')),
                ('fone', models.CharField(max_length=12, verbose_name='Telefone de contato *')),
                ('is_active', models.BooleanField(default=True, help_text='Se ativo, o curso pode ser usado no sistema', verbose_name='Ativo')),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, verbose_name='Hash')),
                ('coordenador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='coordenador', to=settings.AUTH_USER_MODEL, verbose_name='Coordenador da Unidade de Atendimento *')),
            ],
            options={
                'verbose_name': 'unidade',
                'verbose_name_plural': 'unidadess',
                'ordering': ['nome'],
            },
        ),
    ]
