# Generated by Django 3.0.4 on 2023-05-04 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='* Campo obrigatório', max_length=200, verbose_name='Nome completo *')),
                ('cpf', models.CharField(help_text='* Somente os números', max_length=11, unique=True, verbose_name='CPF *')),
                ('email', models.EmailField(max_length=200, verbose_name='Email do paciente ou do responsável *')),
                ('is_active', models.BooleanField(default=False, help_text='Se ativo, o paciente pode realizar triagens e consultas', verbose_name='Ativo')),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, verbose_name='Hash')),
            ],
            options={
                'verbose_name': 'paciente',
                'verbose_name_plural': 'pacientes',
                'ordering': ['-is_active', 'nome'],
            },
        ),
    ]
