# Generated by Django 3.0.4 on 2023-05-11 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='data_nascimento',
            field=models.DateField(help_text='Use dd/mm/aaaa', max_length=10, null=True, verbose_name='Data de nascimento *'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='sexo',
            field=models.CharField(choices=[('FEMININO', 'Feminino'), ('MASCULINO', 'Masculino')], help_text='* Campos obrigatórios', max_length=10, null=True, verbose_name='Sexo *'),
        ),
    ]
