# Generated by Django 3.0.4 on 2023-04-13 14:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medicamento', '0001_initial'),
        ('unidade', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(help_text='Use dd/mm/aaaa', max_length=10, verbose_name='Data da consulta ')),
                ('hora', models.TimeField(help_text='Use hh:mm', max_length=10, verbose_name='Hora da consulta ')),
                ('paciente', models.CharField(help_text='* indica campos obrigatórios', max_length=100, verbose_name='Informe o nome completo do paciente *')),
                ('prescricao', models.TextField(help_text='* indica campos obrigatórios', max_length=1000, verbose_name='Prescrição *')),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, verbose_name='Hash')),
                ('medicamentos', models.ManyToManyField(blank=True, help_text='Para selecionar ou deselecionar um medicamento pressione CTRL + Botão Esquerdo do mouse ou Command + Botão Esquerdo do mouse', null=True, related_name='medicamento', to='medicamento.Medicamento', verbose_name='Medicamento(s)')),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='medico', to=settings.AUTH_USER_MODEL, verbose_name='Médico na consulta *')),
                ('unidade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='unidade_consulta', to='unidade.Unidade', verbose_name='Unidade de Atendimento *')),
            ],
            options={
                'verbose_name': 'consulta',
                'verbose_name_plural': 'consultas',
                'ordering': ['-data', '-hora', 'paciente'],
                'unique_together': {('data', 'hora', 'paciente')},
            },
        ),
    ]
