# Generated by Django 3.0.4 on 2023-05-11 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('triagem', '0008_auto_20230511_1100'),
        ('consulta', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulta',
            name='paciente_triagem',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='paciente_triagem', to='triagem.Triagem', verbose_name='Paciente vindo da triagem *'),
        ),
    ]
