# Generated by Django 3.0.4 on 2023-05-11 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('triagem', '0008_auto_20230511_1100'),
        ('consulta', '0002_consulta_paciente_triagem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consulta',
            options={'ordering': ['-data', '-hora', 'paciente_triagem__paciente2__nome'], 'verbose_name': 'consulta', 'verbose_name_plural': 'consultas'},
        ),
        migrations.AlterUniqueTogether(
            name='consulta',
            unique_together={('data', 'hora', 'paciente_triagem')},
        ),
        migrations.RemoveField(
            model_name='consulta',
            name='paciente',
        ),
    ]
