# Generated by Django 3.0.4 on 2023-03-30 13:13

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medicamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_real', models.CharField(help_text='* Campo obrigatório', max_length=100, unique=True, verbose_name='Nome real do medicamento *')),
                ('nome_fantasia', models.CharField(help_text='* Campo obrigatório', max_length=100, verbose_name='Nome fantasia do medicamento *')),
                ('tarja', models.CharField(choices=[('BRANCA', 'Branca'), ('AMARELA', 'Amarela'), ('VERMELHA', 'Vermelha'), ('PRETA', 'Preta')], help_text='* Campo obrigatório', max_length=10, verbose_name='Tarja do medicamento *')),
                ('tipo', models.CharField(choices=[('CÁPSULA', 'Cápsula'), ('COMPRIMIDO', 'Comprimido'), ('LÍQUIDO', 'Líquido')], help_text='* Campo obrigatório', max_length=10, verbose_name='Tipo do medicamento *')),
                ('quantidade', models.CharField(help_text='Informe a quantidade e a unidade. Por exemplo, 75 mg ou 10 ml ou 15 comprimidos.', max_length=20, verbose_name='Quantidade do medicamento *')),
                ('is_active', models.BooleanField(default=True, help_text='Se ativo, o curso pode ser usado no sistema', verbose_name='Ativo')),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, verbose_name='Hash')),
            ],
            options={
                'verbose_name': 'medicamento',
                'verbose_name_plural': 'medicamentos',
                'ordering': ['tarja', 'nome_real'],
            },
            managers=[
                ('medicamentos_ativos', django.db.models.manager.Manager()),
            ],
        ),
    ]
