# Generated by Django 3.0.4 on 2023-04-20 14:06

import django.contrib.auth.models
from django.db import migrations, models
import usuario.models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_auto_20201119_1719'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='usuario',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
                ('administradores', usuario.models.AdministradorAtivoManager()),
                ('enfermeiros', usuario.models.EnfermeiroAtivoManager()),
                ('tecnicos', usuario.models.TecnicoAtivoManager()),
                ('medicos', usuario.models.MedicoAtivoManager()),
                ('tecnicos_enfermeiros', usuario.models.TecnicoEnfermeiroAtivoManager()),
            ],
        ),
        migrations.AlterField(
            model_name='usuario',
            name='tipo',
            field=models.CharField(choices=[('ADMINISTRADOR', 'Administrador'), ('ENFERMEIRO', 'Enfermeiro'), ('MÉDICO', 'Médico'), ('TÉCNICO', 'Técnico')], default='TÉCNICO', help_text='* Campos obrigatórios', max_length=15, verbose_name='Tipo do usuário *'),
        ),
    ]
