# Generated by Django 3.0.4 on 2020-11-26 22:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('unidade', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Triagem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(help_text='Use dd/mm/aaaa', max_length=10, verbose_name='Data da triagem ')),
                ('hora', models.TimeField(help_text='Use hh:mm', max_length=10, verbose_name='Hora da triagem ')),
                ('paciente', models.CharField(help_text='* indica campos obrigatórios', max_length=100, verbose_name='Informe o nome completo do paciente *')),
                ('data_nascimento', models.DateField(help_text='Use dd/mm/aaaa', max_length=10, verbose_name='Data de nascimento *')),
                ('altura', models.DecimalField(decimal_places=2, max_digits=2, verbose_name='Altura em metros *')),
                ('peso', models.DecimalField(decimal_places=2, max_digits=3, verbose_name='Peso em kg *')),
                ('tem_febre', models.BooleanField(default=False, verbose_name='Tem febre ?')),
                ('tem_dor_cabeca', models.BooleanField(default=False, verbose_name='Tem dor de cabeça ?')),
                ('tem_secrecao_espirros', models.BooleanField(default=False, verbose_name='Tem secreção nasal ou espirros ?')),
                ('tem_irritacao_garganta', models.BooleanField(default=False, verbose_name='Tem irritação de garganta ?')),
                ('tem_tosse', models.BooleanField(default=False, verbose_name='Tem tosse seca ?')),
                ('tem_dificuldade_respiratoria', models.BooleanField(default=False, verbose_name='Tem dificuldade respiratória ?')),
                ('tem_dores_corpo', models.BooleanField(default=False, verbose_name='Tem dores no corpo ?')),
                ('tem_diarreia', models.BooleanField(default=False, verbose_name='Tem diarréia ?')),
                ('viajou', models.BooleanField(default=False, verbose_name='Viajou nos últimos 14 dias para algum local com casos confirmados de COVID 19 ?')),
                ('contatou', models.BooleanField(default=False, verbose_name='Esteve em contato no últimos 14 dias com alguém com quadro diagnosticado de COVID 19 ?')),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, verbose_name='Hash')),
                ('responsavel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='responsavel', to=settings.AUTH_USER_MODEL, verbose_name='Responsável pela triagem *')),
                ('unidade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='unidade', to='unidade.Unidade', verbose_name='Unidade de Atendimento *')),
            ],
            options={
                'verbose_name': 'triagem',
                'verbose_name_plural': 'triagenss',
                'ordering': ['-data', '-hora', 'paciente'],
                'unique_together': {('data', 'hora', 'paciente')},
            },
        ),
    ]
