# Generated by Django 3.0.4 on 2020-11-26 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triagem', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='triagem',
            name='altura',
            field=models.DecimalField(decimal_places=3, max_digits=3, verbose_name='Altura em metros *'),
        ),
        migrations.AlterField(
            model_name='triagem',
            name='peso',
            field=models.DecimalField(decimal_places=3, max_digits=3, verbose_name='Peso em kg *'),
        ),
    ]
