# Generated by Django 3.0.4 on 2023-04-20 14:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triagem', '0003_auto_20201126_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='triagem',
            name='peso',
            field=models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(400.0)], verbose_name='Peso em kg *'),
        ),
    ]
