# Generated by Django 3.0.4 on 2023-05-11 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('triagem', '0006_auto_20230504_1112'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='triagem',
            name='data_nascimento',
        ),
    ]
